import Config

one_month_seconds = 60 * 60 * 24 * 30

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :bank, BankWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :bank, Oban,
  engine: Oban.Engines.Basic,
  queues: [default: 10],
  repo: Bank.Repo,
  plugins: [
    {Oban.Plugins.Pruner, max_age: one_month_seconds},
    {Oban.Plugins.Lifeline, rescue_after: :timer.minutes(30)}
  ]

config :bank, Bank.Repo, pool_size: 10

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Bank.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
