name: Tests

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  test:
    # if: |
    #   (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    name: Tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        elixir:
          - 1.18.4
        # Allowed versions: https://builds.hex.pm/builds/otp/ubuntu-24.04/builds.txt
        otp:
          - 28.0.1
    services:
      postgres:
        image: postgres:17.5-alpine3.22
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 25s
        env:
          POSTGRES_USER: postgres_test
          POSTGRES_PASSWORD: postgres_test
          POSTGRES_DB: postgres

    env:
      MIX_ENV: test
      PG_HOST: localhost

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir ${{ matrix.elixir }} & OTP ${{ matrix.otp }}
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}

      - name: Restore compile cache
        uses: actions/cache@v4
        with:
          path: _build/test
          key:  ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-cache
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-cache
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-deps-cache
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-deps-cache
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - name: Install deps & compile
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
          mix compile --warnings-as-errors

      - name: Create and migrate database
        run: |
          # wait for Postgres to be ready
          until pg_isready -h localhost -U postgres; do
            echo "Waiting for Postgres..."
            sleep 1
          done
          mix ecto.create
          mix ecto.migrate

      - name: Run tests
        run: mix test
